// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqbx5D3K8dUn8COvsu1mXD6GuwubNjLlQ',
    appId: '1:552651360053:web:02e267b8ba66eff3432e7c',
    messagingSenderId: '552651360053',
    projectId: 'puntodeventa-movil-tvz',
    authDomain: 'puntodeventa-movil-tvz.firebaseapp.com',
    storageBucket: 'puntodeventa-movil-tvz.firebasestorage.app',
    measurementId: 'G-58KQ6P0VHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi9f3TdwL2zk4WfImrSjH2ZeoiVu-r5pc',
    appId: '1:552651360053:android:7ee45aa78ea86d68432e7c',
    messagingSenderId: '552651360053',
    projectId: 'puntodeventa-movil-tvz',
    storageBucket: 'puntodeventa-movil-tvz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZanJS-gLEEgHZqCHW4sneWYdbhjU47mc',
    appId: '1:552651360053:ios:5bd1520cd7d72294432e7c',
    messagingSenderId: '552651360053',
    projectId: 'puntodeventa-movil-tvz',
    storageBucket: 'puntodeventa-movil-tvz.firebasestorage.app',
    iosBundleId: 'com.example.puntoDeVentaMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZanJS-gLEEgHZqCHW4sneWYdbhjU47mc',
    appId: '1:552651360053:ios:5bd1520cd7d72294432e7c',
    messagingSenderId: '552651360053',
    projectId: 'puntodeventa-movil-tvz',
    storageBucket: 'puntodeventa-movil-tvz.firebasestorage.app',
    iosBundleId: 'com.example.puntoDeVentaMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqbx5D3K8dUn8COvsu1mXD6GuwubNjLlQ',
    appId: '1:552651360053:web:412cdbba0996f063432e7c',
    messagingSenderId: '552651360053',
    projectId: 'puntodeventa-movil-tvz',
    authDomain: 'puntodeventa-movil-tvz.firebaseapp.com',
    storageBucket: 'puntodeventa-movil-tvz.firebasestorage.app',
    measurementId: 'G-SK6XECDZN6',
  );

}